# Generated by Django 4.1 on 2024-09-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInsideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_inside', models.ImageField(upload_to='car_inside/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inside_images', to='taxi.car')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.car')),
            ],
        ),
    ]
